{% set name = "python-ffmpeg" %}
{% set version = "2.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 19ac80af5a064a2f53c245af1a909b2d7648ea045500d96d3bcd507b88d43dc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyee
    - typing_extensions
    - ffmpeg

test:
  imports:
    - ffmpeg
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/jonghwanhyeon/python-ffmpeg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A python binding for FFmpeg which provides sync and async APIs
  description: |
    A python binding for FFmpeg which provides sync and async APIs
  doc_url: https://python-ffmpeg.readthedocs.io
  dev_url: https://github.com/jonghwanhyeon/python-ffmpeg

extra:
  recipe-maintainers:
    - lorepirri
